name: Feature Request
description: I have an idea to improve this project.

body:
  - type: markdown
    attributes:
      value: |
        Before opening a feature request, please search for the behaviour in the existing feature pull requests. 
        
        ---
        
        Thank you for taking the time to file a feature request. To address this feature request as fast as possible, we need some information.
